name: exhaled
description: Breathing Techniques
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^4.0.1
  equatable: ^1.2.0
  freezed_annotation: ^0.11.0
  injectable: ^0.4.0+1
  get_it: ^4.0.2
  google_fonts: ^1.1.0
  flutter_feather_icons: ^1.0.3

dev_dependencies:
  build_runner: ^1.10.0
  freezed: ^0.11.2
  injectable_generator: ^0.4.1

flutter:
  uses-material-design: true
